architecture-beta
    group context
    group aws(vscode-icons:file-type-aws) in context
    group region(fa6-solid:font-awesome)[Region] in aws
    group private_subnet(bi:cloud-check)[Private subnet] in region
    group public_subnet(bi:cloud-check)[Public subnet] in region
    
    service route(logos:aws-route53)[Route53] in public_subnet
    service clodfront(logos:aws-cloudfront)[CloudFront] in public_subnet
    service waf(logos:aws-waf)[WAF] in public_subnet
    service cw(logos:aws-cloudwatch)[CloudWatch] in private_subnet
    service cognito(logos:aws-cognito)[Cognito] in private_subnet
    service s3(logos:aws-s3)[Host] in private_subnet
    service users(fa6-solid:users-gear)[Usuarios] in context
    
    route:B <--> T:waf
    waf:B <--> T:clodfront
    clodfront:R <--> L:s3
    users:R <--> L:route
